vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        hobby_images:
            uri_prefix: /images/hobby_images
            upload_destination: '%kernel.project_dir%/public/images/hobby_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer